title: PeruJUG
author: ytachi
email: ytaloborjam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Comunidad de @java en Perú y @javaee_guardian

twitter_username: perujug
github_username:  ytachi0026

sass:
    style: compressed