title: PeruJUG
author: PeruJUG
email: xxxxx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Comunidad de @java en Perú y @javaee_guardian

twitter_username: perujug
github_username:  xxxxx

sass:
    style: compressed